spring:
  application:
    name: graphql-api
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  datasource:
#    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true


graphql:
  servlet:
    enabled: true
    mapping: /graphql
    corsEnabled: true

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint: /graphql
  cdn:
    enabled: false
    version: 0.11.11

logging:
  level:
    org.hibernate.SQL: debug
